# Generated by Django 5.1.7 on 2025-04-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "add_needed_fields_to_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="original_url",
            field=models.URLField(
                blank=True,
                help_text="Original media URL from Telegram",
                max_length=500,
                null=True,
            ),
        ),
    ]
