# Generated by Django 5.1.7 on 2025-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        # Забираємо додавання поля, бо колонка вже існує в базі даних
        # Міграція стає порожньою, але її запис буде в базі даних
    ]
