# Generated by Django 5.1.7 on 2025-04-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0007_add_needs_auth_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramsession",
            name="auth_token",
            field=models.CharField(
                blank=True,
                help_text="Token for authorizing this session via bot",
                max_length=255,
                null=True,
            ),
        ),
    ]
