[build]
builder = "NIXPACKS"
buildCommand = "echo 'Building application...'"

[deploy]
startCommand = "bash start_services.sh"
healthcheckPath = "/health.html"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[metrics]
port = 3000
path = "/metrics"

[[services]]
name = "web"
port = 8080
protocol = "http"
internal = false

[[services]]
name = "health"
port = 3000
protocol = "http"
internal = false

[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc", "lsof", "netcat", "procps"] 