[build]
builder = "NIXPACKS"
buildCommand = "chmod +x railway_fix.sh && python manage.py collectstatic --noinput"

[deploy]
startCommand = "bash railway_fix.sh && gunicorn core.wsgi --log-file -"
healthcheckPath = "/health.html"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc"] 