-- Drop tables if they exist
DROP TABLE IF EXISTS admin_panel_message CASCADE;
DROP TABLE IF EXISTS admin_panel_channel CASCADE;
DROP TABLE IF EXISTS admin_panel_category CASCADE;
DROP TABLE IF EXISTS admin_panel_telegramsession CASCADE;
DROP TABLE IF EXISTS django_migrations CASCADE;
DROP TABLE IF EXISTS django_admin_log CASCADE;
DROP TABLE IF EXISTS django_content_type CASCADE;
DROP TABLE IF EXISTS auth_permission CASCADE;
DROP TABLE IF EXISTS auth_group_permissions CASCADE;
DROP TABLE IF EXISTS auth_group CASCADE;
DROP TABLE IF EXISTS auth_user_groups CASCADE;
DROP TABLE IF EXISTS auth_user_user_permissions CASCADE;
DROP TABLE IF EXISTS auth_user CASCADE;
DROP TABLE IF EXISTS django_session CASCADE;