# Generated by Django 5.1.7 on 2025-04-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_fix_telegramsession_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramsession",
            name="needs_auth",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if this session needs manual authentication",
            ),
        ),
    ]
