# Generated by Django 5.1.7 on 2025-04-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="admin_panel_channel_efb64e_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="admin_panel_message_81d7fe_idx",
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="last_parsed",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="telegram_id",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="telegram_username",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="title",
        ),
        migrations.RemoveField(
            model_name="telegramsession",
            name="session_data",
        ),
        migrations.AddField(
            model_name="message",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="messages/"),
        ),
        migrations.AddField(
            model_name="message",
            name="media_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="telegram_channel_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="telegram_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="telegram_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="channel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admin_panel.category"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="channel",
            name="url",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admin_panel.channel"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name="message",
            name="date",
        ),
        migrations.RemoveField(
            model_name="message",
            name="has_audio",
        ),
        migrations.RemoveField(
            model_name="message",
            name="has_document",
        ),
        migrations.RemoveField(
            model_name="message",
            name="has_image",
        ),
        migrations.RemoveField(
            model_name="message",
            name="has_video",
        ),
        migrations.RemoveField(
            model_name="message",
            name="message_id",
        ),
    ]
