# Generated by Django 5.1.7 on 2025-04-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_telegramsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="admin_panel.telegramsession",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channels",
                to="admin_panel.telegramsession",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="session_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="admin_panel.telegramsession",
            ),
        ),
        migrations.AddField(
            model_name="telegramsession",
            name="session_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
