# Generated by Django 5.1.7 on 2025-04-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramsession",
            name="session_string",
            field=models.TextField(blank=True, null=True),
        ),
    ]
