# Generated by Django 5.1.7 on 2025-04-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_category_session_channel_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramsession",
            name="session_data",
            field=models.TextField(
                blank=True, help_text="Base64 encoded session data", null=True
            ),
        ),
    ]
