# Generated by Django 5.1.7 on 2025-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_telegramsession_session_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="telegram_id",
            field=models.CharField(
                blank=True, help_text="Telegram channel ID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                help_text="Telegram username (without @)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Official channel title from Telegram",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="url",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
