# Generated by Django 5.1.7 on 2025-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_fix_auth_conflict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botsettings",
            name="auth_guide_text",
        ),
        migrations.RemoveField(
            model_name="botsettings",
            name="bot_name",
        ),
        migrations.RemoveField(
            model_name="botsettings",
            name="bot_username",
        ),
        migrations.RemoveField(
            model_name="botsettings",
            name="menu_style",
        ),
        migrations.RemoveField(
            model_name="botsettings",
            name="welcome_message",
        ),
        migrations.AddField(
            model_name="botsettings",
            name="bot_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="default_api_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="default_api_id",
            field=models.IntegerField(default=2496),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="max_messages_per_channel",
            field=models.IntegerField(
                default=10, help_text="Maximum number of messages to fetch per channel"
            ),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="polling_interval",
            field=models.IntegerField(
                default=30, help_text="How often to check for new messages (in seconds)"
            ),
        ),
        migrations.AlterField(
            model_name="telegramsession",
            name="api_hash",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="telegramsession",
            name="api_id",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="telegramsession",
            name="auth_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="telegramsession",
            name="needs_auth",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="telegramsession",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="telegramsession",
            name="session_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="telegramsession",
            name="verification_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
