# Generated by Django 5.1.7 on 2025-04-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_category_description_category_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramsession",
            name="needs_auth",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this session needs manual authentication",
            ),
        ),
    ]
