# Generated by Django 5.1.7 on 2025-04-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_category_description_telegramsession_needs_auth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramsession",
            name="needs_auth",
        ),
    ]
