# Generated by Django 5.1.7 on 2025-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0009_add_bot_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramsession",
            name="session_data",
            field=models.TextField(
                blank=True,
                help_text="Encoded session data for persistent storage",
                null=True,
            ),
        ),
    ]
