# Generated by Django 5.1.7 on 2025-04-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_add_auth_token_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_username",
                    models.CharField(
                        default="Channels_hunt_bot",
                        help_text="Username of your Telegram bot (without @)",
                        max_length=100,
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(
                        default="Channel Parser Bot",
                        help_text="Display name of your bot",
                        max_length=100,
                    ),
                ),
                (
                    "auth_guide_text",
                    models.TextField(
                        default="Please follow these steps to authorize your Telegram account",
                        help_text="Text shown during authorization process",
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        default="Welcome to the Channel Parser Bot. Use the menu below:",
                        help_text="Welcome message shown to users",
                    ),
                ),
                (
                    "menu_style",
                    models.CharField(
                        choices=[
                            ("default", "Default Layout"),
                            ("compact", "Compact Layout"),
                            ("expanded", "Expanded Layout"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bot Settings",
                "verbose_name_plural": "Bot Settings",
            },
        ),
    ]
