# Generated by Django 5.1.7 on 2025-04-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_create_tables_from_scratch"),
        ("admin_panel", "fix_telegramsession_created_at"),
    ]

    operations = []
